env:
  node: false
  browser: false
  es6: true
globals:
  require: readonly
  exports: readonly
rules:
  eslint-disable prefer-object-spread: off
  prefer-object-spread: off
  new-cap: off
parserOptions:
  ecmaVersion: 2015
