plugins:
  "@bercow/link-adjacent": {}
  "@bercow/spawn":
    command: npx
    command-win32: npx.cmd
    argv:
      - c8
      - --100
      - --include
      - $RELATIVE_MAIN_PATH
      - --
      - node
      - --unhandled-rejections=strict
      - $RELATIVE_TEST_PATH
