root: true
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - prettier
rules:
  lines-between-class-members: off
  camelcase: off
  no-param-reassign: off
  valid-typeof: off
  spaced-comment: off
  no-shadow: off
  max-classes-per-file: off
  no-unused-vars:
    - error
    - vars: all
      args: none
      ignoreRestSiblings: false
  import/prefer-default-export: off
  class-methods-use-this: off
