
globals:
  globalThis: readonly
  console: readonly
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 2021
  sourceType: module
plugins:
  - local
rules:
  no-undef:
    - error
    - typeof: true
  local/no-globals:
    - error
    - globalThis
    - console
  no-unused-vars:
    - error
    - vars: all
      varsIgnorePattern: "^_"
      args: all
      argsIgnorePattern: "^_"
      caughtErrors: all
      caughtErrorsIgnorePattern: "^_"
      ignoreRestSiblings: false
  arrow-body-style: [error, as-needed]
  consistent-return: error
  no-lone-blocks: error
  no-mixed-operators: [error, {allowSamePrecedence: false}]
  no-use-before-define: error
  no-useless-rename: error
  object-shorthand: [error, always]
  prefer-const: [error, {destructuring: all}]
  prefer-rest-params: error
  prefer-template: error
  require-unicode-regexp: error
  import/first: error
  import/no-extraneous-dependencies: error
  import/no-unresolved: error
  import/no-useless-path-segments: error
