root: true
extends: [airbnb-base, prettier]
rules:
  lines-between-class-members: off
  camelcase:
    - error
    - properties: never
  no-param-reassign: off
  valid-typeof: off
  spaced-comment: off
  no-shadow: off
  max-classes-per-file: off
  no-unused-vars:
    - error
    - vars: all
      args: none
      ignoreRestSiblings: false
  import/prefer-default-export: off
  class-methods-use-this: off
