root: true
extends:
  - eslint:recommended
  - plugin:import/recommended
globals:
  console: readonly
env:
  commonjs: true
  es6: true
  es2017: true
rules:
  no-console:
    - warn
  no-unused-vars:
    - error
    - { args: none }
parserOptions:
  ecmaVersion: 2020
  sourceType: module
