repositoryUrl: https://github.com/applandinc/appmap-agent-js.git
tagFormat: v${version}
dryRun: true
ci: true
branches:
  - name: alpha
    channel: next
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/npm'
  - '@semantic-release/git'
  - '@semantic-release/github'
