arch: arm64
os: linux
dist: focal
language: node_js
node_js: [12]
cache: npm

services:
  - mysql
  - postgresql

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run test-integration

deploy:
  - provider: script
    # skip_cleanup: true
    cleanup: false  # keep semantic release! (and npm modules?)
    script: npm run deploy
    on:
      branch: main

# env:
#   global:
#     - MYSQL_TCP_PORT=3307
#     - PGPORT=5433
#     - PGUSER=appmap
