arch: arm64
os: linux
dist: xenial
language: node_js
node_js: [lts/*]
cache: npm

# # https://unix.stackexchange.com/questions/342952/curl-write-http-code-to-stderr-or-to-file
# # 7.63
# before_install:
#   - sudo apt-get -y install libxml2-dev

install:
  - npm install

script:
  - npm run lint
  - npm run test

deploy:
  - provider: script
    skip_cleanup: true # keep semantic release! (and npm modules?)
    script: npm run deploy
    on:
      branch: alpha
