arch: arm64
os: linux
dist: focal
language: node_js
node_js: [14]
cache: npm

install:
  - npm install

services:
  - postgresql

script:
  - npm run lint
  - npm run test-unit
  - npm run test-integration

deploy:
  - provider: script
    skip_cleanup: true # keep semantic release! (and npm modules?)
    # edge: true
    # cleanup: false
    script: npm run deploy
    on:
      branch: main
