arch: arm64
os: linux
dist: xenial
language: node_js
node_js: [lts/*]
cache: npm

install:
  - npm install

script:
  - npm run lint
  - npm run test

deploy:
  - provider: script
    skip_cleanup: true # keep semantic release! (and npm modules?)
    script: npm run deploy
    on:
      branch: alpha
