arch: arm64
os: linux
dist: xenial
language: node_js
node_js: [lts/*]
cache: npm

install:
  - npm install

script:
  - npm run prettier
  - npm run eslint
  - npm run test

deploy:
  - provider: script
    skip_cleanup: false
    script: npm run deploy
