arch: arm64
os: linux
dist: focal
language: node_js
cache: npm

install:
  - npm install

stages:
  - build
  - test
  - deploy

script:
  - npm run test-unit
  - npm run test-integration

jobs:
  include:
    - stage: build
      node_js: 16
      script:
        - npm run build
        - npm run format
        - npm run lint
    - stage: test
      node_js: 14
      services:
        - postgresql
      script:
        - npm run test-unit
        - npm run test-integration
    - stage: test
      node_js: 16
      services:
        - postgresql
      script:
        - npm run test-unit
        - npm run test-integration
    - stage: deploy
      node_js: 16
      script: npm run deploy
      branches: main
