arch: amd64
os: linux
dist: focal
language: node_js
cache: npm

install:
  - npm install
  - npm run build

stages:
  - lint
  - test
  - deploy

script:
  - npm run test-unit
  - npm run test-integration

jobs:
  include:
    - stage: lint
      node_js: 16
      script:
        - npm run lint
    - stage: test
      node_js: 14
      script:
        - npm run test-unit
        - npm run test-integration
    - stage: test
      node_js: 16
      script:
        - npm run test-unit
        - npm run test-integration
    - stage: deploy
      node_js: 16
      script:
        - npm run format
        - npm run deploy
      branches: main
