default:
  test: spy
  prod: null
dependencies:
  spy:
    - assert
    - util
  node-tcp: []
  node-http1:
    - assert
    - util
    - uuid
  node-http2:
    - util
  inline:
    - assert
    - util
    - backend
