type: object
additionalProperties: false
properties:
  extends: {type: string}
  enabled: {type: boolean}
  escape-prefix:
    type: string
    pattern: "^[a-zA-Z_$][a-zA-Z_$-9]*$"
  output-dir: {type: string}
  app-name: {type: string}
  name: {type: string}
  map-name: {type: string}
  git-dir: {type: string}
  feature: {type: string}
  feature-group: {type: string}
  labels:
    type: array
    items: {type: string}
  recorder-name: {type: string}
  recording-defined-class: {type: string}
  recording-method-id: {type: string}
  frameworks:
    type: array
    items:
      type: object
      additionalProperties: false
      required: ["name", "version"]
      properties:
        name: {type: string}
        version: {type: string}
  language-engine: {type: string}
  language-version:
    enum:
      - "5"
      - "5.1"
      - "6"
      - "2015"
      - "7"
      - "2016"
      - "8"
      - "2017"
      - "9"
      - "2018"
      - "10"
      - "2019"
      - "11"
      - "2020"
      - "12"
      - "2021"
  packages:
    type: array
    items:
      anyOf:
        - {type: string}
        - type: object
          additionalProperties: false
          properties:
            dist: {type: string}
            path: {type: string}
            shallow: {type: boolean}
            exclude:
              type: array
              items: {type: string}
  exclude:
    type: array
    items: {type: string}
